### ISSUE TITLE
Dirichlet Discrete Not Working with Mixture Model

### ISSUE THREAD

**Issue by jzf2101** [datamicroscopes/mixturemodel#8]
When I try to define a model with a dirichlet discrete I get the following error

`ValueError: expected type <class 'microscopes.models.model_descriptor'> for parameter, but got instance of type <type 'builtin_function_or_method’>`

**Comment by tdhopper** [comment]
resolved by [this](https://github.com/datamicroscopes/common/commit/566560e41585406d300225fda987fc653fb3ca9d)
